import re

jar_deps = []

for jarfile in glob(['*.jar']):
  name = 'jars__' + re.sub(r'^.*/([^/]+)\.jar$', r'\1', jarfile)
  jar_deps.append(':' + name)

  prebuilt_jar(
    name = name,
    binary_jar = jarfile,
  )

android_library(
  name = 'deps',
  exported_deps = jar_deps,
  visibility = [
    'PUBLIC',
  ],
)
