maven('com.squareup.okhttp:okhttp:2.4.0')
maven('com.jakewharton.timber:timber:3.1.0')

android_library(
    name = 'deps',
    deps = [
        ':okhttp',
        ':timber'

    ],
    visibility = ['PUBLIC'],
)
